app = "aternos-bot-12345"  # ← 世界でユニークな名前に変えてね
primary_region = "nrt"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  processes = ["app"]

